# Copyright 2021 Province of British Columbia
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and limitations under the License.

parks2017R <-raster(file.path(spatialOutDir,"parks2017R.tif"), format="GTiff") %>%
  mask(AOI) %>%
  crop(AOI) %>%
  aggregate(fact=pixSize)
res(parks2017R)
saveRDS(parks2017R, file = 'tmp/AOI/parks2017R')

#Source surface generated by BC_HumanFootprint repo
source_surface<-raster(file.path(SpatialDir,"source_surface.tif"), format="GTiff")
source_surface_AOI <-source_surface %>%
  mask(AOI) %>%
  crop(AOI) %>%
  aggregate(fact=pixSize)
res(source_surface_AOI)
saveRDS(source_surface_AOI, file = 'tmp/AOI/source_surface_AOI')


#Resistance surface generated by BC_HumanFootprint repo
resistance_surface<-raster(file.path(SpatialDir,paste("resistance_surface.tif",sep="")))
resistance_surface_AOI<-resistance_surface %>%
  mask(AOI) %>%
  crop(AOI) %>%
  aggregate(fact=pixSize)
res(resistance_surface_AOI)
saveRDS(resistance_surface_AOI, file = 'tmp/AOI/resistance_surface_AOI')

hist(resistance_surface_AOI,
     main = "Distribution of Human Footprint",
     xlab = "Score", ylab = "Frequency",
     col = "springgreen")

#Clip map features
parks2017<-readRDS(file= 'tmp/parks2017') %>%
  st_buffer(dist=0) %>%
  st_intersection(AOI)
saveRDS(parks2017, file = 'tmp/AOI/parks2017')

HillShade <-raster(file.path(GISLibrary,'GRIDS/hillshade_BC.tif')) %>%
  mask(AOI) %>%
  crop(AOI)

lakes<-readRDS(file= 'tmp/lakes') %>%
  st_buffer(dist=0) %>%
  st_intersection(AOI)
saveRDS(lakes, file = 'tmp/AOI/lakes')

Blakes<-readRDS(file= 'tmp/Blakes') %>%
  st_buffer(dist=0) %>%
  st_intersection(AOI)
saveRDS(Blakes, file = 'tmp/AOI/Blakes')

rivers<-readRDS(file= 'tmp/rivers') %>%
  st_buffer(dist=0) %>%
  st_intersection(AOI)
saveRDS(rivers, file = 'tmp/AOI/rivers')


